 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: 259-446-379
127.0.0.1 - - [29/Oct/2024 12:30:39] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2024 12:31:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2024 12:31:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
 * Detected change in '/usr/local/lib/python3.10/dist-packages/flask/app.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/generativeai/generative_models.py', reloading
 * Detected change in '/home/user/app.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/api_core/gapic_v1/method.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/api_core/retry/retry_unary.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/api_core/retry/retry_base.py', reloading
 * Detected change in '/usr/local/lib/python3.10/dist-packages/google/api_core/timeout.py', reloading
